version: '3.8'

services:
  frontend:
    build: ./hacktum-check24-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./hacktum-check24-backend
    ports:
      - "3001:3001"
    # depends_on:
    #   - postgres
  # postgres:
  #   build:./hacktum-check24-sql
    
