version: '3.8'

services:
  frontend:
    build: ./hacktum-check24-frontend
    env_file: ./.env
    ports:
      - $REACT_HOST_PORT:$REACT_CONTAINER_PORT
    depends_on:
      - backend
  backend:
    build: ./hacktum-check24-backend
    env_file: ./.env
    environment:
      - DB_NAME=$DB_DATABASE_NAME
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_PORT=$POSTGRES_HOST_PORT
      - DB_USER=$DB_USER
      - SERVER_PORT=$NODE_CONTAINER_PORT
      - DB_HOST=localhost
    ports:
      - $NODE_HOST_PORT:$NODE_CONTAINER_PORT
    depends_on:
      - postgres
  postgres:
    build: ./hacktum-check24-postgres
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - $POSTGRES_HOST_PORT:$POSTGRES_CONTAINER_PORT
    